//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMark.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IMark.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        internal static string AboutTxt {
            get {
                return ResourceManager.GetString("AboutTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string AddressTxt {
            get {
                return ResourceManager.GetString("AddressTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Us On.
        /// </summary>
        internal static string CallOnUsTxt {
            get {
                return ResourceManager.GetString("CallOnUsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string ContantUsBtnTxt {
            get {
                return ResourceManager.GetString("ContantUsBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPLORE OTHER SERVICES.
        /// </summary>
        internal static string ExploreOtherSrvcsTxt {
            get {
                return ResourceManager.GetString("ExploreOtherSrvcsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Us.
        /// </summary>
        internal static string FollowUsTxt {
            get {
                return ResourceManager.GetString("FollowUsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait.
        /// </summary>
        internal static string GetInTouchBtnTxt {
            get {
                return ResourceManager.GetString("GetInTouchBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        internal static string GetStartBtnTxt {
            get {
                return ResourceManager.GetString("GetStartBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Home.
        /// </summary>
        internal static string GoToHomeTxt {
            get {
                return ResourceManager.GetString("GoToHomeTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are happy to help You.
        /// </summary>
        internal static string HappyTxt {
            get {
                return ResourceManager.GetString("HappyTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Know More.
        /// </summary>
        internal static string KnwMorTxt {
            get {
                return ResourceManager.GetString("KnwMorTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Comment.
        /// </summary>
        internal static string LeaveCmntTxt {
            get {
                return ResourceManager.GetString("LeaveCmntTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let us know your requirement and.
        /// </summary>
        internal static string LetKnowRqrmntTxt {
            get {
                return ResourceManager.GetString("LetKnowRqrmntTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let us know your requirement and.
        /// </summary>
        internal static string LetUsKnoUrRqmntAndTxt {
            get {
                return ResourceManager.GetString("LetUsKnoUrRqmntAndTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By the same illusion which lifts the horion of the sea to the level of the spector on a hillside, the sable cloud beneath was dished out....
        /// </summary>
        internal static string MediaBuyingExplainTxt {
            get {
                return ResourceManager.GetString("MediaBuyingExplainTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Buying.
        /// </summary>
        internal static string MediaBuyingTxt {
            get {
                return ResourceManager.GetString("MediaBuyingTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Buying Work.
        /// </summary>
        internal static string MediaBuyingWorkTxt {
            get {
                return ResourceManager.GetString("MediaBuyingWorkTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEWS &amp;amp; BLOGS.
        /// </summary>
        internal static string NewsBlogsTxt {
            get {
                return ResourceManager.GetString("NewsBlogsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        internal static string NewsTxt {
            get {
                return ResourceManager.GetString("NewsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string orTxt {
            get {
                return ResourceManager.GetString("orTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Clients.
        /// </summary>
        internal static string OurClientsTxt {
            get {
                return ResourceManager.GetString("OurClientsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUR SERVICES.
        /// </summary>
        internal static string OurServicesTxt {
            get {
                return ResourceManager.GetString("OurServicesTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUR WORK.
        /// </summary>
        internal static string OurWorkTxt {
            get {
                return ResourceManager.GetString("OurWorkTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string ShareTxt {
            get {
                return ResourceManager.GetString("ShareTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotify Technology S.A. is an international media services provider. It is legally domiciled in Luxembourg and is headquartered in Stockholm, Sweden..
        /// </summary>
        internal static string SpotifyExplainTxt {
            get {
                return ResourceManager.GetString("SpotifyExplainTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotify.
        /// </summary>
        internal static string SpotifyTxt {
            get {
                return ResourceManager.GetString("SpotifyTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotify Work.
        /// </summary>
        internal static string SpotifyWorkTxt {
            get {
                return ResourceManager.GetString("SpotifyWorkTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Us.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string SubmitBtnTxt {
            get {
                return ResourceManager.GetString("SubmitBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You.
        /// </summary>
        internal static string ThnkUTxt {
            get {
                return ResourceManager.GetString("ThnkUTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIEW ALL.
        /// </summary>
        internal static string ViewAllTxt {
            get {
                return ResourceManager.GetString("ViewAllTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ll get back you shortly.
        /// </summary>
        internal static string WeWillgetBakShrtlyTxt {
            get {
                return ResourceManager.GetString("WeWillgetBakShrtlyTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we&apos;ll get back to you soon.
        /// </summary>
        internal static string WeWillGetBckToUSoonTxt {
            get {
                return ResourceManager.GetString("WeWillGetBckToUSoonTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Us On.
        /// </summary>
        internal static string WriteUsOnTxt {
            get {
                return ResourceManager.GetString("WriteUsOnTxt", resourceCulture);
            }
        }
    }
}
